### ISSUE TITLE
Drag and drop does not work between sections if the destination section is empty

### ISSUE THREAD

**Issue by DominikButz** [apptekstudios/ASCollectionView#100]
Drag and drop does not work between sections if the destination section is empty.  It works within the same section and also between sections if the destination section has at least one item. 

I created a on drag and drop event function as shown in one of your examples.  

thanks for looking into this.

**Comment by apptekstudios** [comment]
Thanks for creating the issue :)

I couldn’t seem to reproduce the problem so would appreciate it if you can do the following debugging steps.

In ASSectionDataSource there is a function `insertDragItems`... using breakpoints could you please check if this is being called when you attempt to drop onto the empty section? If it is, what is the indexPath that it’s being given? Is the function stopping at any of the guard statements?

**Comment by apptekstudios** [comment]
I have also just noticed Drag&Drop isn't working at all on 13.4 beta so will be investigating that. I will let you know if I find anything relevant to this issue 👍

**Comment by DominikButz** [comment]
Thanks for your answer. 
I set the following break points in the insertDragItems func:
output: 
insertDragItems(_:at:) drop enabled 
insert drag at indexPath section  
so the function is called. 

When the drag and drop succeeds (into an empty section) my app crashes. 
This debug output comes from the function that is called from the .onRemoveItem event: 
destination section 2
destination index path item 1
destination folder routine count 0
insertion index : 1

2020-02-13 14:27:27.456248+0800 ... [23146:541865] Fatal error: Array replace: subrange extends past the end

Both the destination section and the insertion are wrong because  I tried to drag into section 0 from section 2. 
I guess the reason  for the crash  is that the item was removed from index 0 of section 2 but then it is put back to the same index where it came from -  which is index 1 in section 2. that causes the crash because there is no index 0 any more.... 

see the screen shot for better understanding. 

Actually, dragging and dropping into an empty section either doesn't succeed (output: PBItemCollectionServicer connection disconnected.), no output from the insertDragItems function. Or, if the insert function is called, then the app crashes as described above. 



<img width="356" alt="Screenshot 2020-02-13 at 14 34 11" src="https://user-images.githubusercontent.com/5699871/74409284-66baa380-4e71-11ea-886e-fb7eb6a90fb4.png">

This gif shows unsuccessful attempts to drag and drop: 
![Feb-13-2020 15-04-29](https://user-images.githubusercontent.com/5699871/74409776-68389b80-4e72-11ea-9a42-7a64a929ed56.gif)

**Comment by apptekstudios** [comment]
This might be to do with how UICollectionView is reporting the destination index (not accounting for the removed item...). I wonder if you could perform a bounds-check on the destination index, and if it is not within the bounds of the array assume you should insert at `endIndex - 1`

**Comment by DominikButz** [comment]
I actually had done that already but it still doesn't work as expected. 

The  function below is called from the switch event case .onAddItems(items, indexPath). (I had also implemented a remove logic, a function called from the case .onRemoveItem(indexPath):). 

So the result that you see above already has these functions with insertion index correction implemented.  

Currently, it't not too urgent any more to look into this - especially if I'm the only one having this problem) because I switched to another library and customised it to my needs. 

    func insert(routines: [Routine], indexPath: IndexPath) {

        let destinationFolder =  self.routineFolders[indexPath.section]
        var insertionIndex = indexPath.item
        if insertionIndex >= destinationFolder.routines.count {
            insertionIndex = destinationFolder.routines.count   // preventing index out of bounds crash
        }
   
        self.routineFolders[indexPath.section].routines.insert(contentsOf: routines, at: insertionIndex)
       /// database update logic.... 
}

**Comment by apptekstudios** [comment]
I am currently reworking drag & drop functionality in the `dev` branch and will try to test this scenario when designing it 👍

**Comment by DominikButz** [comment]
thanks. it would be great if you could implement drag and drop between sections including **dropping a cell onto a section header.** This is kind of a standard for some mobile and many desktop apps. This is actually necessary especially when the target section has no items. In that case, only the section header is visible, so there is no other area to drag the cell to.
