### ISSUE TITLE
TableView Pull To Refresh not working

### ISSUE THREAD

**Issue by Harout360** [apptekstudios/ASCollectionView#101]
**Describe the bug**
I'm unable to enable pullToRefresh for tableviews. Even the Instafeed demo that uses pull to refresh doesn't actually pull to refresh. See the following code from the demo:
```
ASTableView(sections: sections)
            .tableViewSeparatorsEnabled(false)
            .tableViewOnPullToRefresh { endRefreshing in
                print("PULL TO REFRESH")
                Timer.scheduledTimer(withTimeInterval: 2, repeats: false) { _ in
                    endRefreshing()
                }
        }
        ....
```

Looking into ASTableView, it seems like `func configureRefreshControl(for tv: UITableView)` isn't being called anywhere?

**To Reproduce**
Launch demo, go to instafeed, try pull to refresh

**Expected behaviour**
tableViewOnPullToRefresh enables pull to refresh

**Screenshots**

**Xcode Version:**
- 11.3

**Simulator, Device, Both?**
- Simulator

**Comment by Harout360** [comment]
PR for the fix
https://github.com/apptekstudios/ASCollectionView/pull/102

**Comment by apptekstudios** [comment]
Thankyou for the issue and PR fix! 😄 Merged, and will include in the next release
