### ISSUE TITLE
HELP Wanted. How to use ASCollectionView with dictionary type [Date:[ImageData]]

### ISSUE THREAD

**Issue by CPiersigilli** [apptekstudios/ASCollectionView#104]
For my app for MacOS with Catalyst  I want to use ASCollectionView for view the images.
I have dictionary type `[Date:[ImageData]]` obtained from:
```
self.groupedImagesFromDate = Dictionary(grouping: images) { (image) -> Date in
       return image.dataCreazione!
 }
```
where `ImageData` is:
```
struct ImageData {
    var id:Int
    var uiimage:UIImage
    var location:CLLocation?
    var placeStr:String
    var dataCreazione:Date?
}
```
How can I use ASCollectionView, to see the sections with associated images.
To show the values from `groupedImagesFromDate` I use this code:
```
for key in self.groupedImagesFromDate.keys {
       print("key: \(key)")
       for item in self.groupedImagesFromDate[key]! {
                print("item: \(item.id)")
      }
}
```
but if I insert `ASCollectionView` don't work.
I hope someone will explain how to do it.

**Comment by apptekstudios** [comment]
The problem with a dictionary as your datasource is it has no defined order for its contents. You could definitely sort the contents into an array (eg by date) and use that. Someone posted a similar question [here on stackoverflow](https://stackoverflow.com/questions/56675532/swiftui-iterating-through-dictionary-with-foreach)
