### ISSUE TITLE
Update layout when sizeCategory changes

### ISSUE THREAD

**Issue by markbryanramirez** [apptekstudios/ASCollectionView#105]
How do we force the collectionview to update layout once the user changes the text size?

**Comment by apptekstudios** [comment]
Previously this has been working by default... which iOS version are you testing on? I'll look into it :)

**Comment by markbryanramirez** [comment]
I've been testing on iOS 13.3.1 on iPhone. I used a custom ASCollectionLayout<Section> in my layout

**Comment by markbryanramirez** [comment]
My workaround to force update the layout is add this .id(self.sizeCategory). I know its not pretty. Hope anyone can provide a cleaner approach. Thank you.
