### ISSUE TITLE
Multiple sections with Waterfall layout?

### ISSUE THREAD

**Issue by sjmueller** [apptekstudios/ASCollectionView#108]
I am trying to create the following layout with two sections, one of them being a waterfall layout:

<img src="https://user-images.githubusercontent.com/29085/75728963-37dc6400-5c9e-11ea-893a-44bf740bd8f5.png" width="250" />

However, `ASWaterfallLayout` seems to operate on the whole `ASCollectionView`, rather than on a section level. Is there any way to achieve this layout?

Thanks!

**Comment by sjmueller** [comment]
By the way I also tried [Steve Breen's approach to Waterfall with compositional layouts](https://gist.github.com/breeno/f16330c5ef06075b0fc476c65d9b00d8), the code plugged into `ASCollectionView` is below.

It *almost* works, so close! The problem is that the layout calculates items horizontally alternating between two columns, but the `ASCollectionViewSection`'s content builder seems to render items straight down each column, and the result is everything is in the wrong order and with the wrong sizes.

``` swift
ASCollectionLayoutSection { environment in
    var leadingGroupHeight = CGFloat(0.0)
    var trailingGroupHeight = CGFloat(0.0)
    var leadingGroupItems = [NSCollectionLayoutItem]()
    var trailingGroupItems = [NSCollectionLayoutItem]()
    let items = self.data // the array of items that's fed into ASCollectionViewSection
    let width = (environment.container.contentSize.width - 50) / 2
    
    let totalHeight = items.reduce(0) { $0 + ($1 == .smallHeightButtonCell ? (width / 2) - 15 : (width / 0.75)) }
    let columnHeight = CGFloat(totalHeight / 2.0)
    
    var runningHeight = CGFloat(0.0)
    for index in 0..<items.count {
        let item = items[index]
        let isLeading = index % 2 == 0
        let layoutSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: item == .smallHeightButtonCell ? .absolute(width / 2) : .absolute(width / 0.75))
        let layoutItem = NSCollectionLayoutItem(layoutSize: layoutSize)
        
        runningHeight += width / 0.75
        
        if isLeading {
            leadingGroupItems.append(layoutItem)
            leadingGroupHeight += width / 0.75
        } else {
            trailingGroupItems.append(layoutItem)
            trailingGroupHeight += width / 0.75
        }
    }
    
    let leadingGroupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.5), heightDimension: .absolute(leadingGroupHeight))
    let leadingGroup = NSCollectionLayoutGroup.vertical(layoutSize: leadingGroupSize, subitems:leadingGroupItems)
    
    let trailingGroupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(0.5), heightDimension: .absolute(trailingGroupHeight))
    let trailingGroup = NSCollectionLayoutGroup.vertical(layoutSize: trailingGroupSize, subitems: trailingGroupItems)
    
    let containerGroupSize = NSCollectionLayoutSize(widthDimension: .fractionalWidth(1.0), heightDimension: .absolute(max(leadingGroupHeight, trailingGroupHeight)))
    let containerGroup = NSCollectionLayoutGroup.horizontal(layoutSize: containerGroupSize, subitems: [leadingGroup, trailingGroup])
    
    let section = NSCollectionLayoutSection(group: containerGroup)
    return section
}
```

**Comment by apptekstudios** [comment]
Unfortunately I don't think it's currently possible to achieve a waterfall with the correct left to right order using UICollectionViewCompositionalLayout. Something to consider would be using ASWaterfallLayout and making a section that contains another ASCollectionView (with a horizontal axis) to achieve the orthogonal layout.

It should be fairly straightforward to add support to ASWaterfallLayout for setting the number of columns per section. You would need this to make the orthogonal section only have a single column 👍

**Comment by apptekstudios** [comment]
I have pushed an update for `ASWaterfallLayout` to the dev branch that supports setting columnCount on a perSection basis. This should allow the solution I proposed above 😄 

```swift
var layout: ASCollectionLayout<Int>
	{
		ASCollectionLayout(createCustomLayout: ASWaterfallLayout.init)
		{ layout in
			layout.numberOfColumns = .perSection({ (sectionIndex) in
				switch sectionIndex {
				case 0:
					return .fixed(1) //Single column so that we can nest another collectionView here for orthagonal layout
				default:
					return .adaptive(minWidth: self.columnMinSize)
				}
			})
		}
}

**Comment by apptekstudios** [comment]
The above feature is now in the latest release. You could achieve the layout by using ASWaterfallLayout and a nested collectionView as discussed above. When nesting a collectionView I recommend you mark the section that contains it with the `.cacheCells()` modifier to ensure it is retained even when scrolling offscreen
