### ISSUE TITLE
Bug: Section Header height when estimated height is too big

### ISSUE THREAD

**Issue by soulfoodz** [apptekstudios/ASCollectionView#111]
**Describe the bug**
I'm using estimated height for my header. If I set it too small, the view jumps, but the header becomes the correct size. If I set it too big, the header centers the content in a view that is too big, with equal margin above and below the content. 

**To Reproduce**
I tried by setting way too big estimated Heights on the demo project, but couldn't reproduce. I think it may be related to my header being more complex than just a text view. 

**Expected behaviour**
The header correctly resizes and displays for the height of the content. 

**Screenshots**
![ASCV Header Issue](https://user-images.githubusercontent.com/4706310/76376370-220e1500-6316-11ea-888d-6727d09ee4da.png)

**Xcode Version:**
- 11.3

**Simulator, Device, Both?**
Device

**Comment by apptekstudios** [comment]
Sorry for the delayed response @soulfoodz!  It sounds as though your `HeaderView` is expanding to take up whatever space it is offered... A likely culprit here is a `Spacer` in a VStack, any chance there's something set to take up as much vertical space as it can?

**Comment by soulfoodz** [comment]
@apptekstudios no worries. Thanks for getting back to me at all. The only vertical spacer I have has a height set on it. 
`	var userInfoView: some View {
		VStack(alignment: .leading, spacing: 15) {
			HStack(alignment: .top, spacing: 10) {
				UserAvatarView(userID: userID)
					.frame(width: 100, height: 100)
				
				VStack(alignment: .leading, spacing: 0) {
					Spacer()
						.frame(height: 30)
					UserProfileBioView(user: user)
				}
				
				Spacer()
			}`

**Comment by apptekstudios** [comment]
I haven't been able to reproduce this to figure out the cause sorry! But might suggest an alternative solution:

Try using the view with it's own section instead, eg:
```
ASSection(id: 0) {
 userInfoView
}
ASSection(id: 1, data: ...) {
  ...
}
```

**Comment by soulfoodz** [comment]
I'll try that. Thanks!

**Comment by soulfoodz** [comment]
Just updated to version 1.5 and the estimated Header height is working as expected. Thanks for all the work you guys put into this and the help offered here. It's greatly appreciated.
