### ISSUE TITLE
Large Title of Navigation having issues when setting background color of ASCollectionView

### ISSUE THREAD

**Issue by markbryanramirez** [apptekstudios/ASCollectionView#112]
**Describe the bug**
Large Title of Navigation having issues when setting background color of ASCollectionView

**To Reproduce**
I set .background(Color(.systemGroupedBackground)) in ASCollectionView with NavigationView configured to ouput largetitle.

**Expected behaviour**
Title of Navigation View should animate to small font when scrolling.

**Xcode Version:**
Version 11.3.1

**Simulator, Device, Both?**
Both

**Comment by apptekstudios** [comment]
Sorry for the delayed response @markbryanramirez. If I've understood correctly you are setting a background however it's not expanding under the navigation title? If so try adding `.edgesIgnoringSafeArea(.all)` after the `.background` modifier

**Comment by markbryanramirez** [comment]
It still had that issue. below is image of the navigation bar. 

<img width="465" alt="Screen Shot 2020-03-26 at 9 29 18 PM" src="https://user-images.githubusercontent.com/20696028/77715181-e1b2c600-6fa8-11ea-89da-f9f671c40463.png">

Below is my code:

<img width="597" alt="Screen Shot 2020-03-26 at 9 30 24 PM" src="https://user-images.githubusercontent.com/20696028/77715245-1030a100-6fa9-11ea-8c22-3ac5a781056f.png">

**Comment by apptekstudios** [comment]
This behaviour is due to SwiftUI's `GeometryReader` rather than ASCollectionView. It is preventing UIKit from detecting the collectionView as a scrollView to attach the title to...

What do you need the geometryProxy for in `self.layout(basedOn: geometry)`?

**Comment by apptekstudios** [comment]
If you are using compositionalLayout it should allow you to access the size of the collectionView from the `NSCollectionLayoutEnvironment`

**Comment by markbryanramirez** [comment]
Thanks for feedback. I didn't realize I can access the size through the environment property. Thanks for pointing it out. I just noticed that if I don't set the background property, the large title in navigation view, it works fine. Somehow setting the background property messes up the navigation view.
