### ISSUE TITLE
TODO: Implement MacOS support

### ISSUE THREAD

**Issue by apptekstudios** [apptekstudios/ASCollectionView#12]
Currently this package is iOS only, would be good to expand with support for MacOS

**Comment by nferruzzi** [comment]
just wondering if this is close because the support is done or because has proven to be not needed or too difficult . Thank you

**Comment by apptekstudios** [comment]
Was closed as the library is working well with Catalyst :D

In the long term would like to consider implementing a mac version using NSCollectionView, but we plan to use catalyst so no need at current.
