### ISSUE TITLE
ASCollectionView wrapped in NavigationView doesn't update height.

### ISSUE THREAD

**Issue by rrroyal** [apptekstudios/ASCollectionView#125]
**Describe the bug**
After scrolling, NavigationViewTitle resizes to `.inline` style and ASCollectionView doesn't update its height leaving blank space between NavigationBar and ASCollectionView.

**To Reproduce**
iPhone X, iOS 13.4.5
iPad 7, iPadOS 13.4.5
```swift
@State var dataExample = (0 ..< 30).map { $0 }
var body: some View {
	NavigationView {
		ASCollectionView(data: dataExample, dataID: \.self) { containerItem, _ in
			NavigationLink(destination: VStack { Text("a") }) {
				Text("\(containerItem)")
			}
		}
		.layout {
			.grid(layoutMode: .adaptive(withMinItemSize: 100), itemSpacing: 32, lineSpacing: 9, itemSize: .absolute(110))
		}
		.navigationBarTitle(Text("Hello"), displayMode: .automatic)
	}
}
```

**Expected behaviour**
View should resize after scrolling (just like regular ScrollView in NavigationView would)

**Screenshots**
[View hierarchy](https://imgur.com/a/69pE15l), [App screenshot](https://imgur.com/a/fuU8H2B)

**Xcode Version:**
11.4

**Simulator, Device, Both?**
Device (can't check on simulator)

**Comment by apptekstudios** [comment]
This is a known SwiftUI bug, add `.edgesIgnoringSafeArea(.all)` outside your ASCollectionView and it should work as expected :)

**Comment by rrroyal** [comment]
It works, but when there isn't enough items to fill whole screen ASCollectionView is below NavigationBar

**Comment by apptekstudios** [comment]
That's strange! I think it might be a little bug in UICollectionViewCompositionalLayout as it should be accounting for the safe area. Try also setting `.alwaysBounceVertical(true)` and see if that makes a difference
