### ISSUE TITLE
Headers are getting cached since 1.4.1 (ASTableView)

### ISSUE THREAD

**Issue by aovalenciar** [apptekstudios/ASCollectionView#126]
**General Situation (ASTableView)**

Your library is awesome, I really love it as the native swiftui lists are so limited. But in version 1.4.1 or grater the headers started to stay in cache, even if my model changes. It change only when I scroll.

**My implementation**: I have a SearchBar to filter by name, then when filtering the sections are updated. In version 1.4.0 it is working nice, headers are updated accordingly, but starting 1.4.0 it not longer works.

**Lib version with the bug:**
1.4.2
1.4.1

**Two videos showing the situation (1.4.2 not working --- 1.4.0 working)**

**Lib Version 1.4.2**
As you can see here when I search some one starting with "J" the header stays at "A" until I scroll.
![Lib Version 1 4 0](https://user-images.githubusercontent.com/11918107/78466791-04d52800-76c3-11ea-9f5b-e5d75a241962.gif)

**Lib Version 1.4.0**
Here in this version, the same process. It works as expected.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/11918107/78466956-d1939880-76c4-11ea-8f27-5d26e9a0bbc7.gif)

**Xcode Version:**
11.4 
- The problem occurs both on simulator and device.

**Comment by apptekstudios** [comment]
Thanks for pointing this out! It should be resolved in V1.5.0 (just released) 🎉 

Please let me know if there are still any issues. Note that v1.5 has some changes to modifier names that might prevent it from building initially (eg collectionViewContentInsets → contentInsets, tableViewSeparatorsEnabled → seperatorsEnabled)

**Comment by aovalenciar** [comment]
Thank so much for the quick response and resolution. It's working again 👌👌
