### ISSUE TITLE
Bug: ASTableView row sizing intermittent issue (since v1.4)

### ISSUE THREAD

**Issue by aovalenciar** [apptekstudios/ASCollectionView#130]
**Describe the bug**
Some times rows are not properly sized until you scroll, I will leave here a video and image to better see what I mean.

I have tested couple of versions and its working on 1.3.2 but since 1.4 it is not.
**Last version tested**: 1.5.0

**Image**

As you can see here, the row marked with blue has the correct size but the red one is bigger than others, then it gets the expected size when I scroll. You can see little more detail on the next video. These is not happening on version 1.3.2 of the library.
![IMG_9131](https://user-images.githubusercontent.com/11918107/78511855-6e0d7780-7765-11ea-8b52-76d437a50463.jpg)

**Videos**
As you can see here the row I toggle (**"Kiki" in "K" section of tableview**) its bigger than the other ones until I scroll.
![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/11918107/78511614-b4fa6d80-7763-11ea-8e22-e6a15f9fe665.gif)

**Xcode Version:**
11.4
- The problem occurs both on simulator and device.

**Thank you for your help!**

**Comment by apptekstudios** [comment]
@aovalenciar Can you please test the `dev` branch with your project and see if this is resolved? Thanks! :)

**Comment by iShavgula-TacTill** [comment]
Hello,

Sorry for asking this under this thread:
@aovalenciar could you please tell me how did you set `sectionIndexTitles` for the table view?
thank you
