### ISSUE TITLE
Bug: @State update during overscroll cancels overscroll

### ISSUE THREAD

**Issue by whilesoftware** [apptekstudios/ASCollectionView#134]
**Describe the bug**
When the .onScroll modifier is set, the overscroll behavior becomes jittery and fails to bounce.

**To Reproduce**
Set .onScroll() and scroll to the bottom

**Expected behaviour**
setting .onScroll() should have no side effects

**Xcode Version:**
1.4

**Simulator, Device, Both?**
Occurs on both simulator and device.

**Comment by apptekstudios** [comment]
Hi @whilesoftware, thanks for posting the issue. Can I check, does this happen even when your `onScroll` method is an empty closure?

**Comment by whilesoftware** [comment]
It does not!

The body of my `onScroll` was setting a local @State which was bound to a Text view... so triggering a view update.

**Comment by apptekstudios** [comment]
Okay, so looks like the view update is causing the overscroll to reset... I suspect this is on the UIKit side of things and will have a look if I can find a way to avoid that 👍🏻
