### ISSUE TITLE
[REQUEST] IndexTitles implementation 

### ISSUE THREAD

**Issue by FaizanDurrani** [apptekstudios/ASCollectionView#137]
Something similar to https://developer.apple.com/documentation/uikit/uicollectionviewdatasource/2851455-indextitles to quickly scroll through the collection view.

**Comment by apptekstudios** [comment]
@FaizanDurrani This should be relatively simple to implement. I'm not too familiar with IndexTitles on collection views - any thoughts on the best API to provide this behaviour? I was thinking that each section could have a closure that returns an `IndexTitle` (if desired) or `nil` for a given index path. Would that meet your expected use case?

**Comment by apptekstudios** [comment]
Closing as the `indexTitles` API is not supported on iOS (only tvOS). This is incorrect in the apple documentation.
