### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by Thomas-Vos** [apptekstudios/ASCollectionView#138]
**Describe the bug**
I am unable to include this in a tvOS target. See screenshot for details:
![Screenshot 2020-04-27 at 20 14 44](https://user-images.githubusercontent.com/11077217/80406044-c1399c80-88c3-11ea-8f60-f0996ebec3b9.png)

**To Reproduce**
Steps to reproduce the behaviour:
Open the attached sample project and try to run it on a tvOS simulator.
[AsCollectionViewTvOsSample.zip](https://github.com/apptekstudios/ASCollectionView/files/4541369/AsCollectionViewTvOsSample.zip)

**Expected behaviour**
No errors

**Xcode Version:**
- Version 11.4.1 (11E503a)

**Simulator, Device, Both?**
- I only tried this on a simulator

**Comment by apptekstudios** [comment]
@Thomas-Vos this is due to the unavailability of many UICollectionView APIs on tvOS. You could get this to work by going through and using `#if available` checks to disable those on tvOS.

**Comment by apptekstudios** [comment]
Closing for now as we are unlikely to pursue tvOS support. Would be very welcoming to a PR if someone adds support :)
