### ISSUE TITLE
Invalid version tag for SPM

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#14]
SPM cannot be used to import project.
You need to provide semantic version tags like 0.9.0 not v0.9.

**Comment by janandre** [comment]
Tested with XCode Version 11.2 beta (11B41).
Maybe the released XCode was not so strict.

**Comment by apptekstudios** [comment]
Thanks! You're right that SPM didn't like the git-style version tag. I've now changed it to strict semantic versioning. Just tested in the Xcode 11.1 GM and works now.

**Comment by janandre** [comment]
Perfect,
Now I don't need my fork anymore. :)
