### ISSUE TITLE
Grid elements are randomized

### ISSUE THREAD

**Issue by DanielSelig** [apptekstudios/ASCollectionView#142]
**Describe the bug**
The AdjustableGridScreen elements are randomized.  How do I avoid this?

**Comment by apptekstudios** [comment]
@DanielSelig sorry this is a bug that slipped through review (I've now added numbering to our demo page for it)! I have fixed it and will push a new version shortly.

**Comment by DanielSelig** [comment]
Thanks.  While I have you here, is there a way for the user to drag and reorder the elements and to have the new order persist?

**Comment by apptekstudios** [comment]
The drag and drop logic will update whatever binding you give it, and then it's up to you to persist the updated data. The demo uses @State for demonstration purposes, however you would need to use some sort of model (eg. via ObservedObject) that persists your data as SwiftUI doesn't maintain @State on leaving a screen :)

**Comment by apptekstudios** [comment]
I have pushed version 1.6.3 that resolves this bug 🥳 please make sure you go to `File → swift packages → Update to latest versions` 👍
