### ISSUE TITLE
Installing via SPM 1.6.3 fails to compile

### ISSUE THREAD

**Issue by lawmicha** [apptekstudios/ASCollectionView#147]
**Describe the bug**
Hi, I'm seeing compiler errors like these:

![image](https://user-images.githubusercontent.com/1365977/82772015-bacf0f80-9df2-11ea-912f-0b90bdbdf6be.png)

**To Reproduce**
Steps to reproduce the behaviour:
1. in the xcode project (i'm in a workspace managed by cocoapods)
2. File -> Swift Packages -> Add 
3. choose the project target (not Pod target)
4. Enter https://github.com/apptekstudios/ASCollectionView
5. resolves to 1.6.3

**Expected behaviour**
No compiler errors

**Xcode Version:**
- 11.3.1
Deployment Info - 13.2
Build settings shows Swift 5

**Comment by apptekstudios** [comment]
Hi @lawmicha, I’ll have a look into this later today. First step would be to update XCode as there were some strange compiler bugs in 11.3

**Comment by apptekstudios** [comment]
Closing this issue as I have confirmed it is related to an Xcode bug that is resolved in the current version 👍 Thank you for reporting it, and I appreciate the PR 😃
