### ISSUE TITLE
Cannot Hide Navigation Bar 

### ISSUE THREAD

**Issue by Rspoon3** [apptekstudios/ASCollectionView#151]
**Describe the bug**
If you try to hide the navigation bar on a view with ASCollectionView, the navigation bar always shows to some degree.

**To Reproduce**
On the TagsScreen of the demo project add the following to the outermost VStack: 

.navigationBarTitle("")
.navigationBarHidden(true)
.navigationBarBackButtonHidden(true)

**Expected behaviour**
The navigation bar should be completely hidden, and there should be not available space for it.

**Screenshots**
I colored the outer most VStack red to show that its not taking but the full height.
![Screen Shot 2020-06-01 at 5 26 42 PM](https://user-images.githubusercontent.com/42879920/83456136-20dc1800-a42d-11ea-82c1-5c88000fbb39.png)

**Simulator, Device, Both?**
Tested on Xcode 11.5 simulator

**Comment by apptekstudios** [comment]
Hi Ricky,

Thanks for opening the issue. This looks like some default SwiftUI behaviour unrelated to ASCollectionView. Try setting a non-empty navigation title and you'll see where this space is coming from 👍 

SwiftUI defaults to using the 'large title' style, which is visible even when the nav-bar is hidden. To fix this simply use `.navigationBarTitle("", displayMode: .inline)`

Hope that helps!

**Comment by Rspoon3** [comment]
Thanks for being super responsive👊🏽

I've tried your suggestion and unfortunately that doesn't fix it. You were right that the extra space is due to the large title being the default behavior, however by changing it to be inline, the navigation view is still there, just smaller.

I'm also not sure that it is entirely SwiftUI behavior because if you comment out the ASCollectionView it works as expected. I have included additional screenshots below.

**With the collection view**
![Screen Shot 2020-06-02 at 9 31 14 AM](https://user-images.githubusercontent.com/42879920/83527155-647a6480-a4b5-11ea-9e50-46602880ff5e.png)

![Screen Shot 2020-06-02 at 9 31 50 AM](https://user-images.githubusercontent.com/42879920/83527161-68a68200-a4b5-11ea-9ca8-f5d8692f306e.png)




**Without the collection view**
![Screen Shot 2020-06-02 at 9 32 42 AM](https://user-images.githubusercontent.com/42879920/83527202-79ef8e80-a4b5-11ea-8d93-a0a0d09d6296.png)

![Screen Shot 2020-06-02 at 9 32 35 AM](https://user-images.githubusercontent.com/42879920/83527219-7fe56f80-a4b5-11ea-95cb-46059df32340.png)

**Comment by apptekstudios** [comment]
I'm not sure why this would be happening! Perhaps you have nested multiple NavigationViews? It's a long shot, but try setting `.navigationBarHidden(true)` outside your `NavigationView { ... }` as well.

**Comment by mengdun** [comment]
have the same issue as well

**Comment by apptekstudios** [comment]
@Rspoon3 @mengdun Strangely I can't get this to happen locally, which is making debugging hard. Is this happening only in when presented in a `sheet` modal? Or all of the time?

**Comment by mengdun** [comment]
@apptekstudios  for me it happens all the time, tried to hide the navigation bar in the example app (the AdjustableGridScreen view), it doesn't work, it works to hide navigationbar title or back button, but not hiding the entire nav bar, thanks


<img width="1274" alt="Screen Shot 2020-06-08 at 2 04 44 PM" src="https://user-images.githubusercontent.com/1975479/84064679-0a840e00-a991-11ea-8dc3-b805540e400d.png">

**Comment by Rspoon3** [comment]
@apptekstudios Yes, I ams presenting it in a sheet. In addition to my earlier screenshot, this is the only other code.

<img width="1496" alt="Screen Shot 2020-06-08 at 7 55 35 PM" src="https://user-images.githubusercontent.com/42879920/84091295-06241900-a9c2-11ea-9460-8ba1399e74fa.png">

**Comment by Fox-On-The-Run-NPE** [comment]
I too am seeing this behavior with hidden navigation being un-hidden on data load. See that there is fix in place (YES!). Will this fix be in 1.7.2 release?

**Comment by AngkiZ** [comment]
Adding `.navigationBarTitle("", displayMode: .inline).navigationBarHidden(true).navigationBarBackButtonHidden(true)`  to the item layout  can solve this problem.  
eg:  
```
ASCollectionView(data: dataExample, dataID: \.self) {  item, _ in 
         Color.blue  
                .overlay(Text("\(item)"))  
                .navigationBarTitle("", displayMode: .inline)  
                .navigationBarHidden(true)  
                .navigationBarBackButtonHidden(true)  
  }
```

**Comment by sergdort** [comment]
So it seems like it's a SwiftUI issue as it for some reason tries to access parent's view controller's navigation controller.
Which is happens on ACCollectionView cell will appear, (when it adds internal cell hosting view controller as a child)
<img width="797" alt="Screenshot 2021-06-03 at 14 48 12" src="https://user-images.githubusercontent.com/4622322/120669385-5162f180-c487-11eb-90f2-799c2f43b57e.png">
