### ISSUE TITLE
Fatal error: Reading Environment EditMode outside View.body

### ISSUE THREAD

**Issue by mesheilah** [apptekstudios/ASCollectionView#156]
I'm having a crash on iOS 13.0 devices and simulators,  which happens exactly in `updateCollectionViewSettings` at the line: `let isEditing = parent.editMode?.wrappedValue.isEditing ?? false`

the error is self explanatory :
`Thread 1: Fatal error: Reading Environment<Optional<Binding<EditMode>>> outside View.body`

can be reproduced with ASCollectionView current master version.

is there a workaround for to solve this issue ?

**Comment by apptekstudios** [comment]
Is this only happening on 13.0 and not on 13.1/2/3 etc? I seem to recall this being a SwiftUI bug that was fixed in the later versions of iOS13.

One option would be to simply remove the isEditing lines from `updateCollectionViewSettings` if you're not making use of edit mode.

**Comment by mesheilah** [comment]
> Is this only happening on 13.0 and not on 13.1/2/3 etc? I seem to recall this being a SwiftUI bug that was fixed in the later versions of iOS13.
> 
> One option would be to simply remove the isEditing lines from `updateCollectionViewSettings` if you're not making use of edit mode.

yes it's only happening on iOS 13.0 and Apple ~solved the issue~ changed the behavior on 13.1+, it's not a bug but it's the way how SwiftUI was dealing with any Environment, State, ObservedObject to prevent any access to them outside of View's Body, and this is so weird.

so anyone with iOS 13.0 will not be able to use ASCollectionView unless they update their iOS.

p.s. it's not a crash related to `isEditing` only, but related to any object of type Environment, State and ObservedObject that is used outside the View's Body on iOS 13.0 devices only.
