### ISSUE TITLE
Release latest version to CocoaPods

### ISSUE THREAD

**Issue by kerrmarin** [apptekstudios/ASCollectionView#157]
It appears there have not been any new versions pushed to cocoapods since 1.4.1. It would be good to get the latest version pushed to the trunk spec repo:

https://cocoapods.org/pods/ASCollectionView-SwiftUI

**Comment by mannyvw** [comment]
Yeah have this problem too, also tried to use by adding sdk via xcode, but get an issue with conflicting versions of DifferenceKit that ASCollectionView uses and I assume some other pod that uses it. Can we have an up to date pod please

**Comment by kerrmarin** [comment]
@mannyvw I got around this by having my own repo to host ASCollectionView's latest version instead of trunk. It's not great but

**Comment by apptekstudios** [comment]
Sorry for the slow response! Hmm I thought I had automated pushes to trunk through the CI, must have lost that at some point. Should be up to date now 👍
