### ISSUE TITLE
how to use drag and drop when using FetchedResults as a data source

### ISSUE THREAD

**Issue by donly** [apptekstudios/ASCollectionView#158]
`ASDragDropConfig` use `var dataBinding: Binding<[Data]>?` as init param, but the data source is FetchedResults with `@FetchRequest` can not use to init.

Is there any way to implement, thanks.

**Comment by apptekstudios** [comment]
This is difficult to approach as FetchedResults has an implicit order to its results. Perhaps you could introduce some ordering column to your data model, sort by that, and then adjust those values on reordering? As for applying the drag&drop, I think the current API doesn't have a way to achieve this, but you could fork this library and change the UIKit code / ASDragDropConfig to add other ways to handle drag & drop

**Comment by apptekstudios** [comment]
V1.8.0 will include a way to manually apply drag/drop to your data
![image](https://user-images.githubusercontent.com/13492172/87213162-51856a80-c366-11ea-9af2-5707bdab655d.png)
