### ISSUE TITLE
How can data binding be used for GroupLarge

### ISSUE THREAD

**Issue by pkasson** [apptekstudios/ASCollectionView#159]
The GroupModel is the state for the collection view items, but it is not annotated as such.

How can the GroupLarge and GroupSmall support SwiftUI data binding for the title and contentCount attributes.

**Comment by apptekstudios** [comment]
These are just normal SwiftUI View structs used for the demo project - there's nothing specific about them relevant to ASCollectionView. Check out the WWDC session on Data flow for more info re: properties vs bindings :)
