### ISSUE TITLE
Bug: ASTableView wrong automatic sizing

### ISSUE THREAD

**Issue by aovalenciar** [apptekstudios/ASCollectionView#160]
**Describe the bug**
Rows are not always properly sized on scrolling, I will leave here a video and image to better see what I mean.

I have tested this with the last versions and it's not working (tested in all versions >= 1.5.0).
Last tested version: 1.7.1

The same issue I'm facing on my app is actually happening on the instagram demo app.

**Video**

As you can see here the second row i'ts bigger than the first one (on bottom), and so on with the following rows.

![ezgif com-optimize (1)](https://user-images.githubusercontent.com/11918107/84585070-60154c00-add1-11ea-8af8-f6cf4f1d2480.gif)

**Screenshots**

Here you can see better what I mean, the same behavior on the demo app.

![Simulator Screen Shot - iPhone 11 - 2020-06-13 at 23 30 56](https://user-images.githubusercontent.com/11918107/84585128-ffd2da00-add1-11ea-8c02-dd261073f4bb.PNG)

![Simulator Screen Shot - iPhone 11 - 2020-06-13 at 23 30 44](https://user-images.githubusercontent.com/11918107/84585132-1b3de500-add2-11ea-95d9-e75b6e43735c.PNG)

**Xcode Version:**
11.5

The problem occurs both on simulator and device.

**As I previously said, thank you for this amazing library and thank you for your help!**

**Comment by cltnschlosser** [comment]
Has anyone found this to not be the case when using a collection view. I'm seeing very similar bugs in my own simpler implementation of UITableView in SwiftUI and just wondering if using a collection view has any benefits here.

**Comment by apptekstudios** [comment]
This sizing error seems to be related to safeArea related issues in SwiftUI. Have an open radar and am hopeful it will be fixed for iOS 14.
https://openradar.appspot.com/radar?id=4929616280027136
https://twitter.com/tobeasbrennan/status/1292226699782844416
