### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Phnx777** [apptekstudios/ASCollectionView#163]
Crash on launch

lauch application on simulator se (1-st generation)
iOS 13.0

<img width="1355" alt="Screenshot 2020-07-01 at 19 27 09" src="https://user-images.githubusercontent.com/10783517/86268902-9cb6b500-bbd1-11ea-8e9b-fb24cc88a6a8.png">
<img width="1370" alt="Screenshot 2020-07-01 at 19 26 53" src="https://user-images.githubusercontent.com/10783517/86268907-9e807880-bbd1-11ea-9623-5c7f3537ef55.png">

**Xcode Version:**
 11.5 (11E608c) 

Simulator se (1-st generation)
iOS 13.0
Did not test on real iPhone se 1-st generation

**Comment by apptekstudios** [comment]
Hi @Phnx777, thanks for reporting the issue. Unfortunately this one is a SwiftUI bug in 13.0 that was resolved in future iOS versions. The only workaround is to avoid using environment variables... if you're not using edit mode you could simply remove the `@environment var editMode` and related code.
