### ISSUE TITLE
Horizontal CollectionView on ScrollView disappear after vertical scroll

### ISSUE THREAD

**Issue by Phnx777** [apptekstudios/ASCollectionView#164]
**Describe the bug**
Horizontal CollectionView on ScrollView disappear after vertical scroll

**To Reproduce**
It can be reproduced in Demo.
1) Open "App Store Layout"
2) Scroll the first section to the third item 
3) Scroll screen to the bottom
4) Scroll screen to the top
After this step the content of first section partly/fully disappear

**Expected behaviour**
The content of first section partly/fully don't disappear

**Screenshots**
Screenshot after 2 step
![photo_2020-07-01 21 46 02](https://user-images.githubusercontent.com/10783517/86280378-574fb300-bbe4-11ea-92ac-42b749b96015.jpeg)

Screenshot after 4 step
![photo_2020-07-01 21 45 57](https://user-images.githubusercontent.com/10783517/86280409-6c2c4680-bbe4-11ea-9711-376b79e3a24d.jpeg)

**Xcode Version:**
Version 11.5 (11E608c)

**Simulator, Device, Both?**
Simulator iOS 13.5 all devices
Device: iPhone 11 Pro Max iOS 13.5

**Comment by donly** [comment]
Same with #90
