### ISSUE TITLE
In Xcode 12.0 beta 2 - Demo App causes a fatal error encountered during compilation

### ISSUE THREAD

**Issue by siliconsorcery** [apptekstudios/ASCollectionView#165]
**Describe the bug**
Xcode 12.0 beta 2 compiler crashes while building ASCollectionView Demo (v1.7.1 or v1.8.0WIP)

**To Reproduce**
Install Xcode 12.0 beta 2
Clone ASCollectionView and open in Xcode
Build

**Expected behaviour**
No crashes of development tools.
App builds and runs on iOS 13+

**Software**
Xcode 12.0 beta 2
MacOS 10.15.5

**Comment by zntfdr** [comment]
Just tried in X12b4, seems to work fine 🎉 

<img width="1048" alt="Screen Shot 2020-08-08 at 9 36 29 AM" src="https://user-images.githubusercontent.com/5277837/89700714-a662d380-d95a-11ea-95e7-f35274912367.png">

**Comment by apptekstudios** [comment]
Seems to have been an issue with the beta. Building without issues in X12b4 👍
