### ISSUE TITLE
Request: WatchOS Support

### ISSUE THREAD

**Issue by NickAtGit** [apptekstudios/ASCollectionView#166]
It doesn't seem to work on watchOS. Is there any plan to get it to work on the watch?

Thanks

**Comment by apptekstudios** [comment]
Hi Nick, unfortunately because we’re using UIKit under-the-hood this library can’t be ported to watchOS. However, there are some purely SwiftUI grid libraries that might meet your needs on the watch 🙂

**Comment by NickAtGit** [comment]
Hi @apptekstudios could you point me to a suitable one?

**Comment by apptekstudios** [comment]
I haven’t used any myself, but this one looks reasonable https://github.com/pietropizzi/GridStack
