### ISSUE TITLE
Cannot convert value of type 'ASSection<Int>' to closure result type 'ViewArrayBuilder.Wrapper'

### ISSUE THREAD

**Issue by brandtdaniels** [apptekstudios/ASCollectionView#184]
Cannot convert value of type 'ASSection<Int>' to closure result type 'ViewArrayBuilder.Wrapper'

For myself and others, what does this mean?

**Comment by brandtdaniels** [comment]
It seems to be related to when I create an ASCollectionView that has only one ASSection.

**Comment by apptekstudios** [comment]
This is a limitation of the current implementation of function builders - hopefully with Swift 5.4 this will be fixed. In the meantime, there is another init method that takes a single section as an argument 👍
