### ISSUE TITLE
ASCollectionViewLayoutFlow calculates widths are wrong

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#19]
As a user I want to get a simple flow layout working by using ASCollectionViewLayoutFlow.

Using ASCollectionViewLayoutFlow with simple Text Views does not result in the expected output.
I would expect that the Text can grow in width until the collection view width (vertical scroll) is reached. But even a small text gets truncated at the moment.

**Comment by apptekstudios** [comment]
Try defining your layout using UICollectionViewFlowLayout instead. The new compositional layout seems to fall short when trying to do flow layouts. I'm contemplating removing that ASCollectionViewLayoutFlow and replacing with one using UICollectionViewFlowLayout.

```
ASCollectionView(
            data: store.items,
            layout: .init(layout: {
                let fl = UICollectionViewFlowLayout()
                fl.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
                return fl
            }())
            ) {

}
```

**Comment by apptekstudios** [comment]
@janandre I made a screen in the demo app that serves to test a custom FlowLayout and ObservableObject as a data source. Hopefully this helps!

Thanks for pointing out the problems you're having, it's very helpful to improve this project 👍

**Comment by janandre** [comment]
Thanks a lot! I will try it.

No problem, there is an urgent need for a cool SwiftUI Collection View implementation.
Keep up the good work!

**Comment by apptekstudios** [comment]
Closing this issue 👍 I did end up removing ASCollectionViewLayoutFlow until Compositional Layout gets better support for flow layouts. The new demo screen ("Tags") should provide a good example of how to achieve a flow layout.
