### ISSUE TITLE
Retain cycles related to Hosting Controller caching.

### ISSUE THREAD

**Issue by paulfreeman** [apptekstudios/ASCollectionView#193]
**Description**
I have found some retain cycles in the current version. These appear to be in the area of caching hosting controllers.  Its unclear to me if they are significant, but as a previous issue covered a similar area I am reporting this for checking.
  
**To Reproduce**
 
1 : View detail from demo

(other views also show similar retentions, but this is what I did first time)

a) open ‘Photo Grid’ let cells fill
B) tap on a cell to view the detail 
C) tap to navigate back to home 
D ) Open memory graph,  select filter for leaks in navigator.  The following two retain cycles and their immediate stack traces were. 

**Results**

**I)  Retain cycle from getUpdatedHC  from ASSectionDataSource.swift** 

Line 111:  
 
`>>>	 	hc = ASHostingController(content)`
	 

**II)  Retain cycle from ASPriorityCache.subscript  (x2)** 

Line 112

`>>>          let node = Node(key: key, value: newValue)`

Called by 

ASCollectionView.setupDataSource 

Line 246 

`>>>       self.autoCachingHostingControllers[itemID] = cell.hostingController`

Called by 

ASDiffableDataSourceCollectionView 

Line 69

`>>>       guard let cell = cellProvider(collectionView, indexPath, itemIdentifier) else`

 
**Xcode Version:**
12.1.1

**Device**
iOS 14.1 (iPhone 12 Max Pro)

**Comment by apptekstudios** [comment]
This should be resolved in the `v1.8.0` branch as I have removed the caching behaviour. SwiftUI was behaving strangely in some circumstances when reusing controllers, and there is no apparent performance loss without caching 👍
