### ISSUE TITLE
Is there any way to center the scrolling to the selected cell? 

### ISSUE THREAD

**Issue by davut** [apptekstudios/ASCollectionView#204]
Depending on the selection I want to scroll to the selected cell (center the cell). Example for that can be youtube app where you can select the tags on top and it centers the selected tag.

Here you can see what I am trying to do. If i select the one on the right it should center that cell.
![Screen Shot 2021-03-02 at 9 45 05 PM](https://user-images.githubusercontent.com/27011602/109758646-be24d200-7ba0-11eb-9d9f-c7df69288ea3.png)

**Comment by trevordevelops** [comment]
Update?

**Comment by davut** [comment]
I don't remember how I found a solution but it's fixed
