### ISSUE TITLE
Cannot find 'ASRemoteImageManager' in scope

### ISSUE THREAD

**Issue by schwjustin** [apptekstudios/ASCollectionView#211]
After adding ASCollectionView using the Swift Packages and selecting Dynamic Library, ASRemoteImageManager is not recognized.

Xcode v12.5

<img width="332" alt="Screen Shot 2021-05-28 at 7 36 39 PM" src="https://user-images.githubusercontent.com/18671480/120050761-0dd23880-bfec-11eb-9e09-78fd2b7d6dc5.png">

**Comment by BayramInanc** [comment]
> After adding ASCollectionView using the Swift Packages and selecting Dynamic Library, ASRemoteImageManager is not recognized.
> 
> Xcode v12.5
> 
> <img width="332" alt="Screen Shot 2021-05-28 at 7 36 39 PM" src="https://user-images.githubusercontent.com/18671480/120050761-0dd23880-bfec-11eb-9e09-78fd2b7d6dc5.png">
Do not add dynamic library.
