### ISSUE TITLE
Pod version appears not updated since 1.7.1

### ISSUE THREAD

**Issue by yusufonderd** [apptekstudios/ASCollectionView#222]
It appears there have not been any new versions pushed to cocoapods since 1.7.1. I also try to install latest version of library from swift package manager but it looks not updated in there.

**Comment by chernovolenko** [comment]
I'm also waiting for cocoapod version with a iOS 15 fix. Are there any info about when to expect this?

**Comment by apptekstudios** [comment]
Sorry the pod-spec was added by a contributor and I recommend SPM as the install method.

I have pushed the latest version to the cocoapods trunk
