### ISSUE TITLE
EXC_BAD_ACCESS when choosing release build configuration

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#24]
**Error:**  EXC_BAD_ACCESS (code=1, address=0x0)
**XCode Version:** Version 11.2 beta (11B41)

When selecting release build configuration in my scheme, ASCollectionView crashes.

I tried to track down a bug in my app where the collection view loaded fine in development builds.
The TestFlight version does not crash but is not loading the content on first change of the data behind. When setting the data again, the view loads without crash.
So I thought to run the App as Release Build and now it crashes.

<img width="1217" alt="Bildschirmfoto 2019-10-22 um 08 29 44" src="https://user-images.githubusercontent.com/9200290/67262758-2c825c00-f4a6-11e9-99c8-d0e917504177.png">

**Comment by janandre** [comment]
The collection view is there (without showing data) on view appear.
It crashes in Release Build Configuration when I press a button that is presenting a `.sheet`.
With development configuration all is stable, also the initial data loading is no problem.

**Comment by apptekstudios** [comment]
Now that was a tough one to track down! It seems the swift compiler doesn't like generic subclasses of generic classes (at least in release configuration).

I've reworked the implementation of ASHostingController to avoid a generic subclass and this crash is now fixed :) Tested on both stable XCode and the latest beta 👍

**Comment by janandre** [comment]
Can confirm, this is resolved!
Great work, thanks for that fast fix!
