### ISSUE TITLE
Issue with initial loading on release builds

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#28]
The last days I try to track down a bug that is not there when running my app with XCode development builds. But TestFlight Beta Builds / Production builds have this problem.

The app is SwiftUI from the start.
- ScenesDelegate > NavigationView > Main View
The main view has a `Store` which is set as environment object.
This store is an `OberservableObject` and has an `@published Array`.

The main view contains a vertical scrollview. One subview there is the ASCollectionView.
It basically shows some "Tag buttons" horizontally.

So when I get to this initial Screen, the cells are not shown all the time. The store has loaded the content of the array fine. When navigating to another view the content immediately appears. Also when showing a sheet.

I tried many approaches. But none really worked out long.

I don't know if that is a bug of ASCollectionView or SwiftUI / Combine lifecycle with the Representable views.

**Comment by janandre** [comment]
Update:
The problem is with release builds. BUT not when running them with XCode and debugger.
It's only if the build is installed on the real device and the app is started there normally. (Not from Xcode)

**Comment by janandre** [comment]
I got a work around for my project.
Within the navigation view I first show a loading screen.
The store got a `initialized` variable and only then the main view is shown.
That way the View and ASCollectionView renders right also in Production Builds.

I guess its a reloading issue because the array is created empty as default and shortly after that content is added. All that during loading of the view hierarchy. Think the bug lies there somewhere.

**Comment by apptekstudios** [comment]
Hmm that is a strange issue, my guess would be some sort of SwiftUI lifecycle issue.

I'm curious to see the visual result if you do the following in the `ASCollectionViewCell` class. This is just to check if the cell's `willAppear` method is being called correctly.

Set background to blue in the `setupFor` method:
```swift
func setupFor(id: ASCollectionViewItemUniqueID, hostingController: ASHostingControllerProtocol?)
	{
		self.hostingController = hostingController
		self.id = id
                self.contentView.backgroundColor = .blue // Cells should appear blue if present in hierarchy but not yet called willAppear
	}
```

Set background to orange in the `willAppear` method:
```swift
func willAppear(in vc: UIViewController?)
	{
        ...The usual code...
        self.contentView.backgroundColor = .orange // Cells should appear orange if willAppear has been called
	}
```

**Comment by apptekstudios** [comment]
Please test this with v0.9.5 👍 I made some changes to work around a few SwiftUI lifecycle bugs. Hopefully it has resolved this issue
