### ISSUE TITLE
SwiftUI incorrectly reusing ASCollectionView within TabView (with workaround)

### ISSUE THREAD

**Issue by tarasis** [apptekstudios/ASCollectionView#44]
I have an issue where sometimes the ASCollectionView disappears from a Tab when I go to another tab containing an ASCollectionView. This never happens if I switch to a different tab in-between.

See attached video. The **Following** and **Test** tabs are virtually identical code (basically AdjustableGridScreen with an additional filter text field that isn't visible or being used), except attached to different datasources, and with the observed layout variable renamed incase it was causing an issue.

[MissingASCollectionView.mov.zip](https://github.com/apptekstudios/ASCollectionView/files/3827843/MissingASCollectionView.mov.zip)

The second attached video is a quick hack of the ASCollectionView demo app to add two tabs to the Experimental test. I created another class called SecondGridView, copied the code from "AdjustableGridScreen", adjusting as needed and reversed the posts. I can switch tabs more often before it loses the ASCollectionView but it does happen.

[ASCollectionViewShowingSameMissingASCollectionView.mov.zip](https://github.com/apptekstudios/ASCollectionView/files/3827855/ASCollectionViewShowingSameMissingASCollectionView.mov.zip)

Also I notice that the scroll location in ASCollectionView in one tab, is the same in the other tab even though they should be different. Also that changes to the number of columns in the first tab is reflected in the second tab, even though I've a separate instance of LayoutState called SecondLayoutState and I renamed the variables.

**Comment by apptekstudios** [comment]
This sounds as though SwiftUI is erroneously deciding to use the same underlying ASCollectionView for each screen.

I'm curious, if you use the swiftUI `id` modifier with a different ID on each ASCollectionView does the error still occur? This is obviously very hacky, but I suspect this is a swiftUI bug.

eg:
```swift
ASCollectionView(...) { ...)
    .id("SCREEN1")
```
and 
```swift
ASCollectionView(...) { ...)
    .id("SCREEN2")
```

**Comment by tarasis** [comment]
Should add on the iPhone(6S) I'm running iOS 13.3beta, and on the iPad its iPadOS 13.2. Both exhibit the bug but at different rates. Code compiled in Xcode 11.2.1 GM.

Using the Hacked Demo app:

On the iPad running 13.2, the disappearing ASCollectionView happens as soon as I swap to the second tab from the first tab.

On the iPhone running 13.3beta it only occasionally happens

**Comment by tarasis** [comment]
> This sounds as though SwiftUI is erroneously deciding to use the same underlying ASCollectionView for each screen.
> 
> I'm curious, if you use the swiftUI `id` modifier with a different ID on each ASCollectionView does the error still occur? This is obviously very hacky, but I suspect this is a swiftUI bug.
> 
> eg:
> 
> ```swift
> ASCollectionView(...) { ... }
>     .id("SCREEN1")
> ```
> 
> and
> 
> ```swift
> ASCollectionView(...) { ... }
>     .id("SCREEN2")
> ```

Will give it a try and report back. Agreed that It does sound like a SwiftUI bug and that's what it appears to be doing, although interesting that it correctly keeps the data sources different.

**Comment by tarasis** [comment]
Yes that works great on the iPhone, the column changes only apply to the particular tab. After a bunch of swapping back and forth, there is a momentary glitch which breaks the stepper.

On the iPad, I can change the number of columns in the first tab, but immediately when I swap to the second tab, the stepper breaks and doesn't work. (the -+ suddenly appear above "Number of columns"). Good news is that I have been unable to trigger the missing ASCollectionView! :) 

So lots of SwiftUI bugginess.

SwiftUI is using the same underlying ASCollectionView unless I use the .id("Screen1")/2 hack
Switching Tabs in the Demo App immediately breaks the Stepper on iPadOS 13.2

Now can have separate number of columns between the two tabs
![IMG_8353](https://user-images.githubusercontent.com/3006/68536863-fb38d580-0359-11ea-9301-1b6b31347443.PNG)
![IMG_8354](https://user-images.githubusercontent.com/3006/68536862-faa03f00-0359-11ea-8cbb-56ca1f5dbe28.PNG)

Broken stepper.
![IMG_8355](https://user-images.githubusercontent.com/3006/68536861-faa03f00-0359-11ea-88a3-0401572c13ae.PNG)
![IMG_8356](https://user-images.githubusercontent.com/3006/68536859-faa03f00-0359-11ea-8944-bca339b044e8.PNG)

**Comment by tarasis** [comment]
Not sure whether to keep this issue open. It is a problem, but it is caused by a SwiftUI bug. The .id() hack does work.

The stepper and slider breaking when swapping between tabs is definitely a separate SwiftUI bug. Created a simple project that shows the issue and have submitted a bug report to Apple.

Zipped video shows the controls breaking views are just a VStack, the control and the text view :)
[Slider-Stepper-breaking.MP4.zip](https://github.com/apptekstudios/ASCollectionView/files/3828409/Slider-Stepper-breaking.MP4.zip)
