### ISSUE TITLE
Adding .onLongPressGesture {} breaks scrolling unless you also add .onTapGesture{}

### ISSUE THREAD

**Issue by tarasis** [apptekstudios/ASCollectionView#50]
**Describe the bug**
If you add .onLongPressGesture to whatever is being displayed in ASCollectionView, you can no longer scroll the collection view, unless you manage to touch on the space left by insets.

The workaround appears to be to add .onTapGesture{} before .onLongPressGesture{}. (after doesn't work)

**To Reproduce**
In the ASCollectionView demo app, open AdjustableGridScreen, 
In the **ASCollectionViewSection**Just after creating the **ASRemoteImageView** add 
`.onLongPressGesture {
                        print("LongPress")
  }`

Build and run, and attempt to scroll by swiping on the images.
Add insets, touch in the inset and then drag.

Stop app,
before .onLongPressGesture{} add
`.onTapGesture {
                            print("Tap")
  }`

Build and run the app, swipe to scroll on the image. Scrolling now works as expected.

**Expected behaviour**
The view should continue to scroll with only an .onLongPressGesture added to the view.

**Xcode Version:**
11.2.1GM 

**Simulator, Device, Both?**
Both simulator and device.

**Comment by tarasis** [comment]
Appears to be another SwiftUI Apple Bug, same behaviour happens on a List {} view.

**Comment by apptekstudios** [comment]
Thanks for reporting the issue :)

I think this one is down to SwiftUI and not much we can do unfortunately (other than file a radar). Thanks for coming up with a workaround! Sounds as though the LongPress gesture is swallowing touches and not allowing other simultaneous gestures

**Comment by tarasis** [comment]
Agreed that its SwiftUI, not your class. Felt it was worth flagging incase someone else hits it.

Will be filing a radar shortly :)
