### ISSUE TITLE
Add feature scrollToItem

### ISSUE THREAD

**Issue by jurekbarth** [apptekstudios/ASCollectionView#52]
I have a feature request, that might fit in the scope of your library.

On a UICollectionView we have the possibility to `scrollToItem(at:at:animated:)`  is that somehow already possible or are you planning to add such features? 

Thanks in advance.

**Comment by apptekstudios** [comment]
Thanks @jurekbarth, that sounds like a good addition to make. I should have time in the next few days to implement it.

To give an idea of potential use cases when deciding on the API...
Do you envision this being called in response to a button press? Or when the collectionview appears? Or something else?

**Comment by jurekbarth** [comment]
@apptekstudios awesome! I would use it when the collection view appears. I want to add a photo gallery and therefor mimic what the iOS Photos App does. So i would like to start from the bottom of the collection view with the "newest" images.

**Comment by apptekstudios** [comment]
@jurekbarth This is now implemented in the `dev` branch. I've included a demo page showing this with the photo grid :) After further testing will push this into master.

Please let me know if you've got any other suggestions!

**Comment by jurekbarth** [comment]
@apptekstudios thank you for your efforts. It works as expected and if you read the source code you also see the different possibilities. 
I think yet another example to showcase "scrollTo" specific item might be a nice addition, e.g. `.initialScrollPosition(.centerOnIndexPath(IndexPath(item: 300, section: 0)))` even though i'm not sure if that would be the approach to go for :)

**Comment by apptekstudios** [comment]
Good idea, I'll try to incorporate the scrolling to a particular item into an example at some point! Merging this into master soon 👍
