### ISSUE TITLE
question: automatic height with UICollectionViewFlowLayout

### ISSUE THREAD

**Issue by juliuste** [apptekstudios/ASCollectionView#53]
Hey! First of all, thank you very much for providing this package, it's really useful.

*Dislaimer: I'm sorry for asking a question here, and I completely understand if you don't have time to answer, but I was unable to solve this on my own after digging for quite some time.*

I used the `tags` demo layout in my app. Is there any way to make the Collection view resize automatically to the height of its contents? As you can see in the screenshot provided below, the height is much larger than the actual text. (PS: I directly copied the tags example code, only exchanged the tags for some gibberish text and gave the `ASCollectionView.layout(…)` a background colour.

<img width="223" alt="height issue screenshot" src="https://user-images.githubusercontent.com/1584289/69016512-09f93b00-099f-11ea-9e9a-5c879dbdf42d.png">

**Comment by apptekstudios** [comment]
Thanks for checking out the package 😄

This is quite difficult to achieve with the currently available swiftUI APIs. I've managed to get it working, but not as neatly as I would like 👍 

See the demo project in the [`shrinkToContentSize` branch](https://github.com/apptekstudios/ASCollectionView/tree/shrinkToContentSize)

It requires you to create a @State variable holding an optional CGSize value, and then pass that binding to the `shrinkToContentSize` modifier. I tried to hide this within the implementation, however swiftUI wasn't retaining the size unless I moved the state further up the hierarchy.

**Comment by apptekstudios** [comment]
I'd like to give more thought to the cleanest way to achieve this before moving it to master, so feel free to point your project to that branch in the meantime :)

**Comment by juliuste** [comment]
Thank you very much for the quick response! Unfortunately, I wasn't able to reproduce the fix, previewing the `tags` view in the demo repo on the `shrinkToContentSize` branch gives me the following:

<img width="408" alt="wrong-size" src="https://user-images.githubusercontent.com/1584289/69082036-965b3a80-0a3f-11ea-91b2-2826bd4c2c63.png">

Maybe I did something wrong with my xcode, does the preview look different for you?

**Comment by apptekstudios** [comment]
That's strange, I'm getting the following:
![SimScreenShot](https://user-images.githubusercontent.com/13492172/69100133-3ba9f900-0aa8-11ea-8c16-d9b03b574543.png)

What version of XCode are you running? I might need to test on a different version (I'm on 11.2.1 GM)

**Comment by apptekstudios** [comment]
Ah I just realised you're referring to the XCode Preview. This is expected behaviour unfortunately, as the preview doesn't do a second layout pass (required to retrieve and set the collection height after laying it out). If you press the play button on the preview it should then appear as expected.

**Comment by juliuste** [comment]
Aah, my bad. The preview somehow rendered it wrong, but it's displayed correctly when running the app in the simulator, or when activating the live preview, which probably makes sense given the way this workaround fixes the problem.

So everything should be fine now, thank you very much again for your time and help, I really appreciate it!

**Comment by juliuste** [comment]
One last question, just in case you left it in accidentally: This branch currently always makes the background of the tags green (not only in the demo, but also if you use the package elsewhere). I guess this was for debugging reasons, I just wanted to make sure you left it in intentionally (if so, no problem, I can fork this).

**Comment by apptekstudios** [comment]
Should be fixed in the latest version of the branch :)

**Comment by juliuste** [comment]
PS: If you have any place where one can donate a little for your effort, I would be happy to give $10 for this (I know, not much, but maybe at least enough for a coffee in 🇦🇺)

**Comment by apptekstudios** [comment]
> PS: If you have any place where one can donate a little for your effort, I would be happy to give $10 for this (I know, not much, but maybe at least enough for a coffee in 🇦🇺)

Thanks Julius! I do have a [buymeacoffee page here](https://www.buymeacoffee.com/tobeasbrennan) 😄

Please feel free to make further feature suggestions if you come across things that are missing from the library 👍
