### ISSUE TITLE
Cocoapods support

### ISSUE THREAD

**Issue by randomiser** [apptekstudios/ASCollectionView#57]
Great product. Thanks for making it available. 

Any chance you could set this up to work with Cocoapods? (The online build tool I'm using doesn't support SPM.)

**Comment by apptekstudios** [comment]
Glad you're liking the package @randomiser 😄 

Unfortunately I won't have time in the near future to implement a cocoapod (we've transitioned to using SPM only), but would welcome a PR if you need to do it for your build tool 👍

**Comment by randomiser** [comment]
Sorry for the late response. Decided to move to SPM instead.

**Comment by kerrmarin** [comment]
See #116
