### ISSUE TITLE
Demo for infinite collection view list?

### ISSUE THREAD

**Issue by ryangittings** [apptekstudios/ASCollectionView#60]
Hey, definitely isn’t an issue but it’d be great to get some advice on the best way to implement and infinite loading list (get to the bottom of the section within a scroll view and for it to load more cells). 

Cheers!

**Comment by apptekstudios** [comment]
Good idea! I've gone ahead and added support for an `onReachedBoundary` closure 😄. It is currently in [its own branch here](https://github.com/apptekstudios/ASCollectionView/tree/onReachedBoundary). Will do some further testing before moving it to master - would appreciate feedback if it works for your use case :)

Should be very straightforward from there to load more data when the closure is called with `boundary == .bottom`.

There's example usage in the following pages:
- MagazineLayout page (will print to console on reaching the top/bottom)
- Instafeed page top section (when the top stories collection reaches the left/right will print to console)
- Instafeed page tableview (will load more content when reaching the bottom)

**Comment by apptekstudios** [comment]
This is now supported in the master branch, and is in the latest release V1.2 🎉

**Comment by ryangittings** [comment]
🤙🏻🤙🏻🤙🏻
