### ISSUE TITLE
Feature Request: macOS support

### ISSUE THREAD

**Issue by jhoughjr** [apptekstudios/ASCollectionView#61]
Just importing UIKit means it won't build on Mac.
It's possible conditionally importing AppKit would make it macOS compatible.

**Comment by apptekstudios** [comment]
ASCollectionView is compatible with Mac Catalyst apps (using UIKit) 🎉 

It won’t work with AppKit without some substantial changes as that would require implementing support for NSCollectionView. This isn’t on the roadmap for us, however we would welcome a PR if anyone does implement it 👍
