### ISSUE TITLE
Detail view with NavigationLink resets @ObservedObject

### ISSUE THREAD

**Issue by ryangittings** [apptekstudios/ASCollectionView#63]
Hey,

When using a collection view, the detail view with NavigationLink resets @ObservedObject. I think this has more potential to be a SwiftUI bug, but wondering if there's any workarounds?

Cheers for this great repo!!

**Comment by apptekstudios** [comment]
If I've understood correctly, this is a byproduct of the way swiftUI holds onto state. Easiest workaround would be to pass the observable object from a view higher in the hierarchy than the navigation link.
