### ISSUE TITLE
Thread 1: Fatal error: Index out of range

### ISSUE THREAD

**Issue by ryangittings** [apptekstudios/ASCollectionView#68]
Getting a crash on line 194, `parent.sections[sectionIndex].id` in ASCollectionSwift when the views have dynamic sections:

`Thread 1: Fatal error: Index out of range`. Let me know if I can help with anymore debug!

**Comment by apptekstudios** [comment]
This should now be fixed in the dev branch 👍 UICollectionViewCompositionalLayout was asking for a sections layout when it no longer existed for some reason...

I'll merge to master after some further testing and other changes are ready for the next release :)

**Comment by ryangittings** [comment]
Thanks so much, and thank you for open sourcing this! 😎
