### ISSUE TITLE
Support for RandomAccessCollection when initialise ASCollectionView with sections

### ISSUE THREAD

**Issue by magnas35** [apptekstudios/ASCollectionView#75]
Similar to my earlier problem initialising the collectionView with FetchedResults but this time when trying to use sections. The `data` parameter of ASCollectionViewSection still seems to be expecting an `Array` rather than the `RandomAccessCollection` that describes FetchedResults. Can the change you made to the ASCollectionView initialiser (to accept FetchedResults) be made to the section-wise initialisers?

**Comment by apptekstudios** [comment]
Sorry I must have missed those initialisers! I’m overseas at the moment and only have access to my iPad (so it will be a few days) but will fix that as soon as I can. 

If you want to attempt a fix on your own branch in the meantime: the initialiser that supports RandomAccessCollection should give an idea of the changes required...

Replace the generic for Data (in the <> section) with `DataCollection: RandomAccessCollection` and then change the following types: `[Data]` to`DataCollection`,  `Data` to `DataCollection.Element`)

**Comment by magnas35** [comment]
Ha no problem! I’m on my phone at the moment so will check later. I’m so happy Xcode isn’t available on iOS or we would be in so much trouble. :)

**Comment by apptekstudios** [comment]
This is now fixed in the dev branch :) will be in the next release, but you can point to that branch for now 👍
