### ISSUE TITLE
Cannot embed in a list or form since version 1.2

### ISSUE THREAD

**Issue by coaoac** [apptekstudios/ASCollectionView#76]
**Describe the bug**
When embedding the ASCollectionView in a List or Form it shows an empty cell.

**To Reproduce**
struct Mock: View {
    let data = ["1"]
    var body: some View {
      Form {
             ASCollectionView(data: data, dataID: \.self) { item, _ in
                  Text(item)
             }
       }
    }
}

**Expected behaviour**
It would ve great if the ASCollectionView showed its content and resized the List/Form cell to fit the ASCollectionView size. This behaviour was working in v 1.1.6 even though sometimes the List/Form cell would not update its height properly.

**Screenshots**
in a VStack: 
![with a VStack](https://user-images.githubusercontent.com/73089/72267474-689a0880-3620-11ea-96b4-d4f388b8c853.PNG)

in a Form:
![with a Form](https://user-images.githubusercontent.com/73089/72267501-764f8e00-3620-11ea-8561-5f559f99b1be.PNG)

**Xcode Version:**
11.3 (11C29)

**Simulator, Device, Both?**
- Device (probably both)

**Comment by apptekstudios** [comment]
This seems to be due to SwiftUI ignoring the content size we offer it. There is a workaround...

1) make an @State variable in the view containing your list to hold the contentSize of the ASCollectionView:
```swift
@State var contentSize: CGSize? // This state variable is handed to the collectionView to allow it to store the content size
```

2) tell ASCollectionView to self-size, passing it the above variable:
```swift
ASCollectionView { ... }
	.layout { ... }
	.shrinkToContentSize(isEnabled: true, $contentSize, dimensionToShrink: .vertical)
```

**Comment by apptekstudios** [comment]
This is looking more like a swiftUI bug as I investigate. When in a swiftUI scroll view the UIViewController is never getting moved to a parent (and so the UIKit functions aren’t being called) :/

Will dig further but it might call for a UIKit scrollview instead until they fix that

**Comment by apptekstudios** [comment]
Hmm definitely a SwiftUI bug that's led to this, I've added a workaround [to the dev branch](https://github.com/apptekstudios/ASCollectionView/tree/dev) so that the collectionView will display as expected 🎉 

However, there is a big SwiftUI bug still causing unexpected behaviour... it seems that the contents of ScrollView / List are not getting updated correctly, and if they change in size this is not reflected. I've confirmed this behaviour in a clean SwiftUI project with no ASCollectionView involved.

**Comment by MostafaMazrouh** [comment]
@apptekstudios  I have tried your dev branch and it gas the same bug

![Screen](https://user-images.githubusercontent.com/48998803/73344255-19e0a580-4293-11ea-8408-a94fafb4306f.gif)

**Comment by apptekstudios** [comment]
Testing on 13.3.1 with the latest version of ASCollectionView, this is currently resolved.

Note that for SwiftUI to respect the size of the collectionView you must use `.shrinkToContentSize`. Alternatively use a `.frame` modifier to set a fixed height (and if the contents of the collectionView is larger it will be scrollable)
