### ISSUE TITLE
Crash in Demo project

### ISSUE THREAD

**Issue by gdetari** [apptekstudios/ASCollectionView#78]
**Describe the bug**
The app starts fine, but then any of the options I choose leads to EXC_BAD_ACCESS. Both simulator and device.

**To Reproduce**
Run demo app, tap on any of the options in the list.

**Screenshots**

**Xcode Version:**
11.2.1

**Simulator, Device, Both?**
Both

**Comment by apptekstudios** [comment]
I can’t reproduce this issue, it might be due to one of the bugs in that version of XCode... please try the latest (11.3.1). Please feel free to reopen if it’s still happening then 👍
