### ISSUE TITLE
Weird layout behavior during scrolling

### ISSUE THREAD

**Issue by alexeyprimechaev** [apptekstudios/ASCollectionView#79]
**Describe the bug**

Off-screen views are not loaded and appear truncated, and if a cell changes it's content dynamically, the layout breaks completely on scroll attempt.

**To Reproduce**

Not really sure, I guess just load a large amount of data to the ASCV and apply AlignedFlowLayout (one from the tags screen from the demo).

**Expected behaviour**
Layout _not_ breaking?

**Screenshots**

*Video*

https://imgur.com/uBudbT1

**Xcode Version:**
11.3.1

**Simulator, Device, Both?**
Both

**Comment by 1234igor** [comment]
+++
same issue

**Comment by jorditambillo** [comment]
Similar issue when wrapping `ASCollectionView` in ScrollView. It doesn't appear anymore.

**Comment by ryangittings** [comment]
Similar issue here, my views disappear completely.

**Comment by apptekstudios** [comment]
Sorry for the delayed response, I'm overseas without regular wifi access at the moment!

Definitely something strange going on :/ Is this new behaviour with the new Xcode version (11.3.1) or had it appeared with one of the recent releases of this package?

**Comment by apptekstudios** [comment]
> Similar issue when wrapping `ASCollectionView` in ScrollView. It doesn't appear anymore.

See if the workaround I posted here fixes the embedding in ScrollView :) https://github.com/apptekstudios/ASCollectionView/issues/76

**Comment by alexeyprimechaev** [comment]
> Sorry for the delayed response, I'm overseas without regular wifi access at the moment!
> 
> Definitely something strange going on :/ Is this new behaviour with the new Xcode version (11.3.1) or had it appeared with one of the recent releases of this package?

No biggie, hope you're having a great time, wherever you are! 

I'm not quite sure about the behavior on previous Xcode build, gonna check later today.

**Comment by jorditambillo** [comment]
> > Similar issue when wrapping `ASCollectionView` in ScrollView. It doesn't appear anymore.
> 
> See if the workaround I posted here fixes the embedding in ScrollView :) #76

I have tried this workaround but still doesn't work for Scrollview as the wrapper.

**Comment by apptekstudios** [comment]
Please try the 1.3.1 release and see if this resolves the issues 👍
