### ISSUE TITLE
Section header for Waterfall layout?

### ISSUE THREAD

**Issue by sjmueller** [apptekstudios/ASCollectionView#83]
When adding a `.sectionHeader` modifier to a collectionview with `ASWaterfallLayout`, the section doesn't show up anywhere. If I remove the custom layout, then i see the header just fine.

Is there any current way to achieve a section header with the waterfall layout?

**Comment by apptekstudios** [comment]
I hadn't actually added support yet, however I got a chance today to add it 🎉 

I've pushed it to the [dev branch](https://github.com/apptekstudios/ASCollectionView/tree/dev) 👍 Will move to master with the next release
