### ISSUE TITLE
Trying to pop to a missing destination

### ISSUE THREAD

**Issue by foolbear** [apptekstudios/ASCollectionView#85]
**Describe the bug**
push TagsScreen from RemindersScreen, then back to RemindersScreen...
report "Trying to pop to a missing destination at /BuildRoot/Library/Caches/com.apple.xbs/Sources/Monoceros/Monoceros-39.4.4/UIKit/UIKitNavigationBridge.swift:391"

**To Reproduce**
Steps to reproduce the behaviour:
modify RemindersScreen code like this:
`ASCollectionView
            {
                ASCollectionViewSection<Section>(id: .upper, data: self.upperData)
                { model, _ in
                    NavigationLink(destination: TagsScreen()) {
                        GroupLarge(model: model)
                    }
                }
...
`

**Expected behaviour**
A description of what you expected to happen.

**Screenshots**

**Xcode Version:**
- 

**Simulator, Device, Both?**
- Where is the problem occuring

**Comment by apptekstudios** [comment]
Is this crashing or just logging a message? Sounds quite similar to an old swiftUI bug that got fixed in 13.3.0 #54 

Which version of iOS/XCode is this happening on?

**Comment by foolbear** [comment]
@apptekstudios, not crash, just logging. 
iOS 13.3.1
Xcode 11.3.1

**Comment by magnas35** [comment]
I see exactly the same behaviour and error code in my own app.
Also I just have to run the Demo app > Photo grid (with edit mode, selection) > hit any image > hit Explore (to go back to previous view) = error message in log.

**Comment by c941010623** [comment]
when i only use the code
```
        NavigationView {
            TabView(selection:$selection) {
                List(0..<6) { _ in
                    NavigationLink(destination:Text("fffff")) {
                        Text("GGG")
                    }
                }
            }
            .tabItem {
                Text("首頁")
            }
        }
```
i also get same error
```
Trying to pop to a missing destination at /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/Monoceros/Monoceros-42.22/Shared/NavigationBridge_PhoneTV.swift:205
```

**Comment by skunkworker** [comment]
On Xcode 12.3 I'm seeing this bug when the ASCollectionView is inside of a NavigationView. But the example code above no longer produces this bug.
