### ISSUE TITLE
Feature request: Scroll To Position Programatically (? via Binding)

### ISSUE THREAD

**Issue by adamtow** [apptekstudios/ASCollectionView#89]
I would like to be able to programmatically jump the ASCollectionView to the bottom by way of a binding variable. This would replicate the behavior in the Shortcuts application, where you can tap on the Shortcuts tab bar icon to move the collection view to the bottom.

**Comment by apptekstudios** [comment]
This is a good feature suggestion 😄This is difficult to get right with the state-based setup of SwiftUI but I will have a think about how to achieve this 👍

**Comment by adamtow** [comment]
I made a fork of the 1.2.1 release since the 1.2.2 was not compiling for some reason. I made some modifications so I could access the underlying collection view and a subclass for handling key commands in my app LaunchCuts. Now from my app, I can scroll to the top, bottom, and navigating using the keyboard through the collection view.

**Comment by fredz999** [comment]
How do you access this feature?

**Comment by Rspoon3** [comment]
I would also like a way to scroll to the bottom. Does anyone have more information on this?

**Comment by adamtow** [comment]
I have a new branch of 1.6.3 in my fork that you can look at: https://github.com/adamtow/ascollectionview

I can then include an extension to AS_CollectionViewController wherein I:

- Override the viewDidAppear method
- Add an observer for my scrollToBottom notification
- Call this method when the notification is received:

`objc func keyCommandScrollToBottom(notification: NSNotification?) {
		//debugPrint("ASCollectionView go to bottom via notification")
		let maxOffset = self.collectionView.maxContentOffset
		
		self.collectionView.setContentOffset(.init(x: 0, y: maxOffset.y), animated: true)
}`

**Comment by apptekstudios** [comment]
There will soon be support for setting scroll position via a binding. This is currently supported on the dev branch and will be merged into master soon 🎉

**Comment by apptekstudios** [comment]
Support now in the 1.7.0 release 🎉
