### ISSUE TITLE
Fatal error: Reading Environment<UIEdgeInsets> outside View.body

### ISSUE THREAD

**Issue by sjmueller** [apptekstudios/ASCollectionView#91]
Getting this error only on iPhone 7+ (iPhone X and 11 Pro Max don't exhibit the error)

![image](https://user-images.githubusercontent.com/29085/73626364-78908100-45fd-11ea-8bdd-50290c28506e.png)

I've tried on `V1.2.2`, `master` and `dev` with the same results, and happens regardless if I actually set `contentInsets` on the `ASCollectionView`. I'm using `ASWaterfallLayout`, but other than that pretty standard.

**Comment by apptekstudios** [comment]
Hmm this might be a SwiftUI bug... I’ve double checked and that function is only being called by the UIVCRepresentable functions and nowhere else so based on the documentation there shouldn’t be a problem. Also very strange it’s only on that device, which iOS version is it running?

**Comment by sjmueller** [comment]
The device was running iOS `13.0`, and upgrading it to `13.3.1` fixed the problem. I have another device that is running `13.2` that I tested and works fine, so I'm guessing this bug was either fixed in 13.1 or 13.2.
