### ISSUE TITLE
How to add section headers to custom layouts?

### ISSUE THREAD

**Issue by magnas35** [apptekstudios/ASCollectionView#94]
I saw that you recently added section header support for the WaterfallLayout but how can we add similar support for custom layouts? I can't find the ASWaterfallLayout definition to try to copy the header implementation. Will this be possible do you think? Many thanks.

**Comment by apptekstudios** [comment]
@magnas35 Can you please clarify what you mean by custom layouts? Custom UICollectionViewLayout classes? Or compositional layouts?

If compositional layouts, check the 'App Store' demo page, it demonstrates adding support for headers.

If custom classes, that's up to the layout class to implement... we use `UICollectionView.elementKindSectionHeader` as the supplementary kind for consistency.

**Comment by magnas35** [comment]
Thank you. I looked at the App Store section and all is good!
