### ISSUE TITLE
Layout problem when navigationTitle displayMode is large

### ISSUE THREAD

**Issue by sdaheng** [apptekstudios/ASCollectionView#96]
**Describe the bug**
When set navigationBarTitle`s displayMode to .large and scroll the collectionView. 
There is a gap between navigation bar and collectionView.

**To Reproduce**
Steps to reproduce the behaviour:
In the demo project, PhotoGrideScreen.swift.
Change displayMode to .large.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/1405754/74138909-603bea00-4c2d-11ea-8c02-76d78df14152.png">

**Expected behaviour**

**Screenshots**
<img width="433" alt="image" src="https://user-images.githubusercontent.com/1405754/74138408-87de8280-4c2c-11ea-9faf-aae0c5267360.png">

**Xcode Version:**
- 11.3

**Simulator, Device, Both?**
Both

[20200210-173643-HD.mp4.zip](https://github.com/apptekstudios/ASCollectionView/files/4180097/20200210-173643-HD.mp4.zip)

**Comment by apptekstudios** [comment]
Thanks for creating the issue! Looks like a minor SwiftUI bug... try rotating to landscape and back to portait and voila it works.

I'll have a look if I can find a cause / workaround 👍

**Comment by apptekstudios** [comment]
I used the view debugger and confirmed that SwiftUI isn't propagating the safeArea change properly. Bug is happening at the level of `UIHostingView` which is unfortunately a private class...

However, there is an easy fix! 🎉 ASCollectionView does respect the safeArea, so just tell SwiftUI to ignore safeAreas and our code will step in :) 

Just add the following SwiftUI modifier to the collectionView:
```swift
.edgesIgnoringSafeArea(.all)
```
