### ISSUE TITLE
How to hide/show an ASCollectionViewSection in conditional?

### ISSUE THREAD

**Issue by foolbear** [apptekstudios/ASCollectionView#97]
**Describe the bug**

I found we cannot use if in ASCollectionView, how to hide/show an ASCollectionViewSection in conditional?

```
ASCollectionView
            {
                if somecondition {
                    ASCollectionViewSection<Section>(id: .upper, data: self.upperData)
                    { model, _ in
                            GroupLarge(model: model)
                        }
                    }
              }
...
```

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
A description of what you expected to happen.

**Screenshots**

**Xcode Version:**
- 

**Simulator, Device, Both?**
- Where is the problem occuring

**Comment by DominikButz** [comment]
the model object in your upperData array should be an observable object. then give it a property with the @Published key word, e.g. @Published isOpen = true .
In the closure, you need to put the GroupLarge view into an if condition .. if model.isOpen { GroupLarge.... }  
You can attach a .sectionHeader modifier to the ASCollectionViewSection and e.g. in the section header you put an HStack or just a Text view. To this view, add a .tapGesture modifier or make the view a button.  then toggle the isOpen property.

**Comment by foolbear** [comment]
@DominikButz  No, I need make a ASCollectionViewSection disappeared if condition is false. your solution is emptying items in ASCollectionViewSection, but the ASCollectionViewSection is still here.

**Comment by DominikButz** [comment]
yep, you are right.  The trick is to pass an empty array to the ASCollectionViewSection like this:
ASCollectionViewSection<Section>(id: .upper, data: sectionModelObject.isOpen ? self.upperData : [] .....

**Comment by foolbear** [comment]
@DominikButz 

Yes, but it's not what I want. You know, even if a ASCollectionViewSection has no sub items, It still occupy the space in the ASCollectionView, such as header, footer, background and etc. 

I just want make a ASCollectionViewSection disappeared totally.

**Comment by DominikButz** [comment]
So the user can't hide / unhide the section?  In that case just don't create a section. if your data model has empty arrays, e.g. like this dataModel = [[data...], [],  [data... ]] you might want to remove those empty arrays first. 
I used a similar  approach as the magazine layout example (check out the example project) 

So in the body, the ASCollectionView looks like this 


        ASCollectionView(sections: self.sections)
                            .layout { () -> ASCollectionLayoutSection in
                                .grid(
                                    layoutMode: .adaptive(withMinItemSize: 160),
                                itemSpacing: 15,
                                lineSpacing: 15,
                                itemSize: .estimated(160))
                            }.animation(.spring())


In the section variable, you need to use the map function on your data model. 

I'm not a contributor to his project, I just saw your post while checking if an issue I have already exists. So you might want to wait for a better solution from one of the contributors / creators.

**Comment by foolbear** [comment]
I know, thank you, @DominikButz .
Your layout is very simple, you can try RemindersScreen in the Demo.
I think my desired is a basic function. hiding a ASCollectionViewSection, not just hiding items in ASCollectionViewSection. They are not the same.

**Comment by DominikButz** [comment]
I checked the Reminder layout and this seems to work. 
       ASCollectionViewSection(id: Section.upper, data: self.upperIsShown ?  self.upperData : [])
                { model, _ in
                    GroupLarge(model: model)
                }

if the state variable upperIsShown is set to false, the screen looks like this:

<img width="348" alt="Screenshot 2020-02-11 at 17 34 59" src="https://user-images.githubusercontent.com/5699871/74225028-e7a06080-4cf4-11ea-98cb-4affa09debf5.png">

**Comment by foolbear** [comment]
No, please check top spacing of .list ASCollectionViewSection, it's double as usual. There is a 0 size ASCollectionViewSection(.upper).

**Comment by apptekstudios** [comment]
Thanks for the helpful comments @DominikButz 😊

@foolbear I went ahead and added support for if statements to the function builder. This is now in the master branch, and will be included in the next release. That means you can now do the following:
`if someBoolVariable { ASSection(...) }`

For more complex cases, the approach suggested by Dominik is best... if you construct an array of sections and pass this to the collection view it allows you to map/filter it as desired 👍🏻
