### ISSUE TITLE
support for right to left languages

### ISSUE THREAD

**Issue by mesheilah** [apptekstudios/ASCollectionView#98]
I've tried several ways in order to change the filling of the collection view to be from right to left but to  no avail, I also played with the project localization too.

Can anybody help me with this issue ?

**Comment by apptekstudios** [comment]
I wonder if the setting you are looking for is `UICollectionViewLayout. flipsHorizontallyInOppositeLayoutDirection`.

I will hopefully have time to look into making a setting for this later, but try forking `master` and setting that variable to true on line 87 of `ASCollectionViewLayout.swift`, eg:

```swift
let cvLayout = UICollectionViewCompositionalLayout(sectionProvider: sectionProvider, configuration: config)
cvLayout.flipsHorizontallyInOppositeLayoutDirection = true
registerDecorationViews(cvLayout)
return cvLayout
```

https://developer.apple.com/documentation/uikit/uicollectionviewlayout/2891099-flipshorizontallyinoppositelayou?language=objc

**Comment by apptekstudios** [comment]
Sorry I was mistaken, that property is read-only... Apple docs say you need a custom layout subclass to override it

**Comment by apptekstudios** [comment]
For now it seems this requires a custom layout class, so will close the issue as it's outside the scope of ASCollectionView.
