### ISSUE TITLE
How do I get the position while scrolling ?

### ISSUE THREAD

**Issue by mkalayci35** [apptekstudios/ASCollectionView#99]
How do I get the position while scrolling? I will hide the search bar according to it.

**Comment by Allan121** [comment]
I'm interested in this as well - I'm looking to implement paged scrolling behaviour.

**Comment by apptekstudios** [comment]
For now that could be achieved by jumping outside of SwiftUI and using a custom collectionView delegate. See the MagazineLayout demo for an example of a custom delegate. The delegate function of interest would be `scrollViewDidScroll`.

I'll have a look into making this accessible via a binding, however it doesn't fit very well into a declarative architecture.

**Comment by JanRajtr** [comment]
How this can be achieved when the delegate function `scrollViewDidScroll` cannot be overridden?

**Comment by apptekstudios** [comment]
Hi @mkalayci35 and @Allan121, in the dev branch there is now support for an `onScroll` closure. This will be released in the next version 👍
